"""Raw provider catalog data for deterministic dependency resolution."""

RAW_PROVIDER_CATALOG: tuple[dict[str, object], ...] = (
    {
        "provider": "OpenAI",
        "company": "OpenAI",
        "category": "ai",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("openai", "openai-agents"),
        "env_aliases": ("OPENAI_API_KEY", "OPENAI_BASE_URL"),
        "url_aliases": ("api.openai.com", "openai.azure.com"),
    },
    {
        "provider": "Anthropic",
        "company": "Anthropic",
        "category": "ai",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("anthropic", "@anthropic-ai/sdk"),
        "env_aliases": ("ANTHROPIC_API_KEY",),
        "url_aliases": ("api.anthropic.com",),
    },
    {
        "provider": "Google Cloud",
        "company": "Google",
        "category": "cloud",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": (
            "google-cloud",
            "google-cloud-storage",
            "google-cloud-pubsub",
            "@google-cloud/storage",
        ),
        "env_aliases": ("GOOGLE_APPLICATION_CREDENTIALS", "GOOGLE_CLOUD_PROJECT"),
        "url_aliases": ("googleapis.com",),
    },
    {
        "provider": "Google Maps",
        "company": "Google",
        "category": "maps",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@googlemaps/google-maps-services-js",),
        "env_aliases": ("GOOGLE_MAPS_API_KEY",),
        "url_aliases": ("maps.googleapis.com",),
    },
    {
        "provider": "AWS",
        "company": "Amazon",
        "category": "cloud",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("aws-sdk", "boto3", "botocore", "@aws-sdk", "awssdk"),
        "env_aliases": ("AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"),
        "url_aliases": ("amazonaws.com",),
    },
    {
        "provider": "AWS S3",
        "company": "Amazon",
        "category": "storage",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("s3fs", "awssdk.s3"),
        "env_aliases": ("S3_BUCKET", "S3_ENDPOINT"),
        "url_aliases": ("s3.amazonaws.com",),
        "image_aliases": ("minio",),
        "scheme_aliases": ("s3",),
    },
    {
        "provider": "AWS SQS",
        "company": "Amazon",
        "category": "messaging",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("awssdk.sqs",),
        "env_aliases": ("SQS_QUEUE_URL",),
        "url_aliases": ("sqs.",),
    },
    {
        "provider": "AWS DynamoDB",
        "company": "Amazon",
        "category": "database",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("awssdk.dynamodbv2", "dynamodb"),
        "env_aliases": ("DYNAMODB_TABLE",),
        "url_aliases": ("dynamodb.",),
    },
    {
        "provider": "Azure",
        "company": "Microsoft",
        "category": "cloud",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("azure.identity", "azure.core", "@azure/identity"),
        "env_aliases": ("AZURE_CLIENT_ID", "AZURE_TENANT_ID", "AZURE_SUBSCRIPTION_ID"),
        "url_aliases": ("azure.com", "microsoftonline.com"),
    },
    {
        "provider": "Azure Service Bus",
        "company": "Microsoft",
        "category": "messaging",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("azure.messaging.servicebus",),
        "env_aliases": ("SERVICEBUS_CONNECTION_STRING",),
        "url_aliases": ("servicebus.windows.net",),
    },
    {
        "provider": "Azure Blob Storage",
        "company": "Microsoft",
        "category": "storage",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("azure.storage.blobs", "@azure/storage-blob"),
        "env_aliases": ("AZURE_STORAGE_CONNECTION_STRING", "AZURE_STORAGE_ACCOUNT"),
        "url_aliases": ("blob.core.windows.net",),
    },
    {
        "provider": "Azure Cosmos DB",
        "company": "Microsoft",
        "category": "database",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("azure.cosmos",),
        "env_aliases": ("COSMOS_CONNECTION_STRING",),
        "url_aliases": ("documents.azure.com",),
    },
    {
        "provider": "Stripe",
        "company": "Stripe",
        "category": "payment",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("stripe", "stripe.net", "@stripe/stripe-js"),
        "env_aliases": ("STRIPE_API_KEY", "STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"),
        "url_aliases": ("stripe.com", "api.stripe.com"),
    },
    {
        "provider": "PayPal",
        "company": "PayPal",
        "category": "payment",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("paypal", "@paypal/checkout-server-sdk"),
        "env_aliases": ("PAYPAL_CLIENT_ID", "PAYPAL_CLIENT_SECRET"),
        "url_aliases": ("paypal.com", "api-m.paypal.com"),
    },
    {
        "provider": "Adyen",
        "company": "Adyen",
        "category": "payment",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("adyen", "@adyen/api-library"),
        "env_aliases": ("ADYEN_API_KEY",),
        "url_aliases": ("adyen.com",),
    },
    {
        "provider": "Auth0",
        "company": "Okta",
        "category": "authentication",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("auth0", "@auth0/auth0-spa-js", "@auth0/nextjs-auth0"),
        "env_aliases": ("AUTH0_DOMAIN", "AUTH0_CLIENT_ID", "AUTH0_CLIENT_SECRET"),
        "url_aliases": ("auth0.com",),
    },
    {
        "provider": "Okta",
        "company": "Okta",
        "category": "authentication",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@okta/okta-auth-js", "@okta/okta-sdk-nodejs", "okta"),
        "env_aliases": ("OKTA_DOMAIN", "OKTA_CLIENT_ID", "OKTA_CLIENT_SECRET"),
        "url_aliases": ("okta.com",),
    },
    {
        "provider": "Twilio",
        "company": "Twilio",
        "category": "communication",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("twilio",),
        "env_aliases": ("TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_API_KEY"),
        "url_aliases": ("twilio.com",),
    },
    {
        "provider": "SendGrid",
        "company": "Twilio",
        "category": "email",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("sendgrid", "@sendgrid/mail"),
        "env_aliases": ("SENDGRID_API_KEY",),
        "url_aliases": ("sendgrid.com",),
    },
    {
        "provider": "Slack",
        "company": "Salesforce",
        "category": "communication",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("slack_sdk", "@slack/web-api", "@slack/bolt"),
        "env_aliases": ("SLACK_BOT_TOKEN", "SLACK_SIGNING_SECRET", "SLACK_WEBHOOK_URL"),
        "url_aliases": ("slack.com", "hooks.slack.com"),
    },
    {
        "provider": "Datadog",
        "company": "Datadog",
        "category": "monitoring",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("datadog", "datadog.trace", "dd-trace"),
        "env_aliases": ("DATADOG_API_KEY", "DD_API_KEY"),
        "url_aliases": ("datadoghq.com",),
    },
    {
        "provider": "Sentry",
        "company": "Sentry",
        "category": "monitoring",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("sentry-sdk", "@sentry/node", "sentry.aspnetcore"),
        "env_aliases": ("SENTRY_DSN",),
        "url_aliases": ("sentry.io",),
    },
    {
        "provider": "Salesforce",
        "company": "Salesforce",
        "category": "crm",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("simple-salesforce", "jsforce"),
        "env_aliases": ("SALESFORCE_CLIENT_ID", "SALESFORCE_USERNAME"),
        "url_aliases": ("salesforce.com", "force.com"),
    },
    {
        "provider": "HubSpot",
        "company": "HubSpot",
        "category": "crm",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@hubspot/api-client", "hubspot-api-client"),
        "env_aliases": ("HUBSPOT_API_KEY", "HUBSPOT_ACCESS_TOKEN"),
        "url_aliases": ("hubapi.com", "hubspot.com"),
    },
    {
        "provider": "Redis",
        "company": "Redis",
        "category": "cache",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("redis", "ioredis", "stackexchange.redis"),
        "env_aliases": ("REDIS_URL", "REDIS_HOST"),
        "url_aliases": ("redis.io", "redis.com"),
        "image_aliases": ("redis", "redis/redis-stack"),
        "scheme_aliases": ("redis", "rediss"),
    },
    {
        "provider": "PostgreSQL",
        "company": "PostgreSQL Global Development Group",
        "category": "database",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("psycopg2", "pg", "npgsql", "postgres", "sqlalchemy"),
        "env_aliases": ("DATABASE_URL", "POSTGRES_URL", "POSTGRES_HOST"),
        "url_aliases": ("postgresql.org",),
        "image_aliases": ("postgres",),
        "scheme_aliases": ("postgres", "postgresql"),
    },
    {
        "provider": "MySQL",
        "company": "Oracle",
        "category": "database",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("mysql", "mysql2", "mysqlconnector", "mysqlclient"),
        "env_aliases": ("MYSQL_URL", "MYSQL_HOST"),
        "url_aliases": ("mysql.com",),
        "image_aliases": ("mysql",),
        "scheme_aliases": ("mysql", "mysql2"),
    },
    {
        "provider": "MongoDB",
        "company": "MongoDB",
        "category": "database",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("mongodb", "mongodb.driver", "mongoose", "pymongo"),
        "env_aliases": ("MONGODB_URI", "MONGO_URL"),
        "url_aliases": ("mongodb.net", "mongodb.com"),
        "image_aliases": ("mongo",),
        "scheme_aliases": ("mongodb", "mongodb+srv"),
    },
    {
        "provider": "Kafka",
        "company": "Confluent",
        "category": "messaging",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("kafka", "confluent-kafka", "confluent.kafka", "kafkajs"),
        "env_aliases": ("KAFKA_BROKERS", "KAFKA_BOOTSTRAP_SERVERS"),
        "url_aliases": ("confluent.cloud",),
        "image_aliases": ("kafka", "confluentinc/cp-kafka"),
        "scheme_aliases": ("kafka",),
    },
    {
        "provider": "RabbitMQ",
        "company": "VMware",
        "category": "messaging",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("rabbitmq", "rabbitmq.client", "amqplib", "pika"),
        "env_aliases": ("RABBITMQ_URL", "RABBITMQ_HOST"),
        "url_aliases": ("rabbitmq.com",),
        "image_aliases": ("rabbitmq",),
        "scheme_aliases": ("amqp", "amqps"),
    },
    {
        "provider": "Elastic",
        "company": "Elastic",
        "category": "search",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("elasticsearch", "@elastic/elasticsearch", "elastic.clients.elasticsearch"),
        "env_aliases": ("ELASTICSEARCH_URL", "ELASTIC_CLOUD_ID"),
        "url_aliases": ("elastic.co", "elasticsearch"),
        "image_aliases": ("elasticsearch",),
        "scheme_aliases": ("elasticsearch",),
    },
    {
        "provider": "Snowflake",
        "company": "Snowflake",
        "category": "analytics",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("snowflake", "snowflake-connector-python", "snowflake-sdk"),
        "env_aliases": ("SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER"),
        "url_aliases": ("snowflakecomputing.com",),
    },
    {
        "provider": "Clerk",
        "company": "Clerk",
        "category": "authentication",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@clerk/clerk-js", "@clerk/nextjs", "@clerk/backend"),
        "env_aliases": ("CLERK_SECRET_KEY", "CLERK_PUBLISHABLE_KEY"),
        "url_aliases": ("clerk.dev", "clerk.com"),
    },
    {
        "provider": "Supabase",
        "company": "Supabase",
        "category": "backend-platform",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@supabase/supabase-js", "supabase"),
        "env_aliases": ("SUPABASE_URL", "SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"),
        "url_aliases": ("supabase.co",),
    },
    {
        "provider": "Firebase",
        "company": "Google",
        "category": "backend-platform",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("firebase", "firebase-admin", "@firebase/app"),
        "env_aliases": ("FIREBASE_CONFIG", "FIREBASE_PROJECT_ID"),
        "url_aliases": ("firebaseio.com", "firebase.google.com"),
    },
    {
        "provider": "Clarity",
        "company": "Microsoft",
        "category": "analytics",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("clarity-js", "@microsoft/clarity"),
        "env_aliases": ("CLARITY_PROJECT_ID",),
        "url_aliases": ("clarity.ms",),
    },
    {
        "provider": "Mixpanel",
        "company": "Mixpanel",
        "category": "analytics",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("mixpanel", "mixpanel-browser"),
        "env_aliases": ("MIXPANEL_TOKEN", "MIXPANEL_PROJECT_TOKEN"),
        "url_aliases": ("mixpanel.com", "api.mixpanel.com"),
    },
    {
        "provider": "Amplitude",
        "company": "Amplitude",
        "category": "analytics",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@amplitude/analytics-browser", "@amplitude/node", "amplitude"),
        "env_aliases": ("AMPLITUDE_API_KEY",),
        "url_aliases": ("amplitude.com", "api2.amplitude.com"),
    },
    {
        "provider": "Segment",
        "company": "Twilio",
        "category": "analytics",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@segment/analytics-node", "@segment/analytics-next", "analytics-node"),
        "env_aliases": ("SEGMENT_WRITE_KEY",),
        "url_aliases": ("segment.io",),
    },
    {
        "provider": "Braze",
        "company": "Braze",
        "category": "communication",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@braze/web-sdk", "braze"),
        "env_aliases": ("BRAZE_API_KEY", "BRAZE_REST_ENDPOINT"),
        "url_aliases": ("braze.com",),
    },
    {
        "provider": "Intercom",
        "company": "Intercom",
        "category": "communication",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("intercom-client", "intercom-web"),
        "env_aliases": ("INTERCOM_ACCESS_TOKEN",),
        "url_aliases": ("intercom.io",),
    },
    {
        "provider": "Mailgun",
        "company": "Sinch",
        "category": "email",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("mailgun.js", "mailgun"),
        "env_aliases": ("MAILGUN_API_KEY", "MAILGUN_DOMAIN"),
        "url_aliases": ("mailgun.net", "mailgun.org"),
    },
    {
        "provider": "Postmark",
        "company": "ActiveCampaign",
        "category": "email",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("postmark",),
        "env_aliases": ("POSTMARK_API_TOKEN", "POSTMARK_SERVER_TOKEN"),
        "url_aliases": ("postmarkapp.com",),
    },
    {
        "provider": "Zendesk",
        "company": "Zendesk",
        "category": "support",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("zendesk", "node-zendesk"),
        "env_aliases": ("ZENDESK_API_TOKEN", "ZENDESK_SUBDOMAIN"),
        "url_aliases": ("zendesk.com",),
    },
    {
        "provider": "PagerDuty",
        "company": "PagerDuty",
        "category": "incident-management",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("pagerduty", "@pagerduty/pdjs"),
        "env_aliases": ("PAGERDUTY_API_KEY", "PAGERDUTY_TOKEN"),
        "url_aliases": ("pagerduty.com",),
    },
    {
        "provider": "Linear",
        "company": "Linear",
        "category": "project-management",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@linear/sdk", "linear"),
        "env_aliases": ("LINEAR_API_KEY",),
        "url_aliases": ("linear.app",),
    },
    {
        "provider": "Jira",
        "company": "Atlassian",
        "category": "project-management",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("jira", "jira-client"),
        "env_aliases": ("JIRA_API_TOKEN", "ATLASSIAN_API_TOKEN"),
        "url_aliases": ("atlassian.net", "jira.com"),
    },
    {
        "provider": "Confluence",
        "company": "Atlassian",
        "category": "documentation",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("confluence", "atlassian-python-api"),
        "env_aliases": ("CONFLUENCE_API_TOKEN",),
        "url_aliases": ("atlassian.net/wiki", "confluence.atlassian.com"),
    },
    {
        "provider": "Notion",
        "company": "Notion",
        "category": "documentation",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("@notionhq/client", "notion-client"),
        "env_aliases": ("NOTION_API_KEY", "NOTION_TOKEN"),
        "url_aliases": ("notion.so",),
    },
    {
        "provider": "GitHub",
        "company": "GitHub",
        "category": "developer-platform",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("pygithub", "@octokit/rest", "github"),
        "env_aliases": ("GITHUB_TOKEN", "GH_TOKEN"),
        "url_aliases": ("api.github.com", "github.com"),
    },
    {
        "provider": "GitLab",
        "company": "GitLab",
        "category": "developer-platform",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("python-gitlab", "@gitbeaker/node"),
        "env_aliases": ("GITLAB_TOKEN",),
        "url_aliases": ("gitlab.com",),
    },
    {
        "provider": "Vercel",
        "company": "Vercel",
        "category": "paas",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("vercel", "@vercel/node"),
        "env_aliases": ("VERCEL_TOKEN", "VERCEL_URL"),
        "url_aliases": ("vercel.app", "vercel.com"),
    },
    {
        "provider": "Netlify",
        "company": "Netlify",
        "category": "paas",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("netlify", "@netlify/functions"),
        "env_aliases": ("NETLIFY_AUTH_TOKEN",),
        "url_aliases": ("netlify.app", "netlify.com"),
    },
    {
        "provider": "Render",
        "company": "Render",
        "category": "paas",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("render",),
        "env_aliases": ("RENDER_API_KEY",),
        "url_aliases": ("onrender.com", "render.com"),
    },
    {
        "provider": "Heroku",
        "company": "Salesforce",
        "category": "paas",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("heroku",),
        "env_aliases": ("HEROKU_API_KEY",),
        "url_aliases": ("herokuapp.com", "heroku.com"),
    },
    {
        "provider": "Fastly",
        "company": "Fastly",
        "category": "edge",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("fastly",),
        "env_aliases": ("FASTLY_API_TOKEN", "FASTLY_SERVICE_ID"),
        "url_aliases": ("fastly.com", "fastly.net"),
    },
    {
        "provider": "Cloudflare",
        "company": "Cloudflare",
        "category": "edge",
        "default_boundary": "TECHNICAL_INFRA",
        "package_aliases": ("cloudflare",),
        "env_aliases": ("CLOUDFLARE_API_TOKEN",),
        "url_aliases": ("cloudflare.com",),
    },
    {
        "provider": "Algolia",
        "company": "Algolia",
        "category": "search",
        "default_boundary": "BUSINESS_SYSTEM",
        "package_aliases": ("algoliasearch",),
        "env_aliases": ("ALGOLIA_API_KEY", "ALGOLIA_APP_ID"),
        "url_aliases": ("algolia.net",),
    },
)
