"""Run Graphify AST extraction as a subprocess and return the parsed graph.json."""

import json
import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from app.domain.exceptions import ExtractionError

logger = logging.getLogger(__name__)

def _locate_graphify_root() -> Path:
    """Return the path to the graphify package root.

    Prefers GRAPHIFY_ROOT env var (set to /graphify inside Docker).
    Falls back to walking up the directory tree looking for the package,
    which works in local development without any env var.
    """
    env_val = os.environ.get("GRAPHIFY_ROOT")
    if env_val:
        return Path(env_val)
    # Walk up from this file until we find a sibling graphify/ directory
    for ancestor in Path(__file__).resolve().parents:
        candidate = ancestor / "graphify"
        if (candidate / "graphify" / "__main__.py").exists():
            return candidate
    raise RuntimeError(
        "Cannot locate graphify root. "
        "Set the GRAPHIFY_ROOT environment variable to the graphify package directory."
    )


_GRAPHIFY_ROOT = _locate_graphify_root()


# Extensions that trigger Graphify's semantic (LLM) extraction pass.
# We drop these via .graphifyignore so the run stays code-only and free.
_GRAPHIFYIGNORE_CONTENT = """\
# Auto-generated by KnowledgeForge — forces code-only AST extraction.
# Graphify requires an LLM API key to process docs/images; we skip them
# here and rely on OpenRouter for C4 inference instead.

# Documentation & markup
*.md
*.mdx
*.qmd
*.rst
*.txt
*.pdf
*.html
*.htm
*.xhtml
*.haml
*.erb
*.slim
*.njk
*.jinja
*.jinja2
*.j2

# Images & media
*.png
*.jpg
*.jpeg
*.gif
*.webp
*.svg
*.ico
*.mp4
*.mov
*.webm
*.mkv
*.mp3
*.wav

# Office & binary docs
*.docx
*.xlsx
*.pptx
*.odt
*.ods
*.odp

# Config / data (non-code)
*.xml
*.yaml
*.yml
*.toml
*.ini
*.cfg
*.conf
*.env
*.lock
*.csv
*.tsv
"""


def run_graphify(repo_path: Path) -> dict:
    """Run Graphify on *repo_path* and return the parsed graph.json dict.

    Only the tree-sitter AST pass is executed (Pass 1 — free, local, no API
    calls).  A .graphifyignore is written to skip docs/images so Graphify
    never requires an LLM key.  C4 inference is done separately via OpenRouter.

    Args:
        repo_path: Absolute path to the cloned repository.

    Returns:
        Parsed graph.json as a Python dict.

    Raises:
        ExtractionError: If Graphify produces no graph.json output.
    """
    _LLM_KEYS_TO_STRIP = {
        "ANTHROPIC_API_KEY",
        "OPENAI_API_KEY",
        "GOOGLE_API_KEY",
        "GEMINI_API_KEY",
        "DEEPSEEK_API_KEY",
        "KIMI_API_KEY",
    }
    env = {k: v for k, v in os.environ.items() if k not in _LLM_KEYS_TO_STRIP}
    env["PYTHONPATH"] = str(_GRAPHIFY_ROOT)

    # Write .graphifyignore so Graphify skips doc/image files and stays code-only.
    # If the repo is read-only (e.g. a :ro Docker mount), build a writable shadow
    # directory: a real dir containing the .graphifyignore file plus one symlink
    # per top-level entry in the original repo.  Graphify finds the ignore file
    # and follows the symlinks for AST extraction — no data is copied.
    graphifyignore = repo_path / ".graphifyignore"
    _ignore_existed = graphifyignore.exists()
    _tmp_ignore_dir: tempfile.TemporaryDirectory | None = None
    scan_path = repo_path

    if not _ignore_existed:
        try:
            graphifyignore.write_text(_GRAPHIFYIGNORE_CONTENT, encoding="utf-8")
        except OSError:
            logger.info("repo_path is read-only; building shadow dir for .graphifyignore")
            _tmp_ignore_dir = tempfile.TemporaryDirectory(prefix="kf_rofs_")
            shadow = Path(_tmp_ignore_dir.name) / repo_path.name
            shadow.mkdir()
            # Drop .graphifyignore into the writable shadow root
            (shadow / ".graphifyignore").write_text(_GRAPHIFYIGNORE_CONTENT, encoding="utf-8")
            # Symlink every top-level entry so graphify sees the full tree
            for entry in repo_path.iterdir():
                if entry.name != ".graphifyignore":
                    (shadow / entry.name).symlink_to(entry)
            scan_path = shadow
            _ignore_existed = False  # cleaned with tmp dir

    try:
        with tempfile.TemporaryDirectory(prefix="kf_graphify_") as tmp_dir:
            cmd = [
                sys.executable, "-m", "graphify",
                "extract", str(scan_path),
                "--out", tmp_dir,
                "--max-workers", str(os.cpu_count() or 4),
            ]
            logger.info("Running graphify: %s", " ".join(cmd))

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=1800,
                env=env,
                cwd=str(_GRAPHIFY_ROOT),
            )

            if result.returncode != 0:
                logger.warning("graphify stderr: %s", result.stderr[-3000:])

            graph_file = Path(tmp_dir) / "graphify-out" / "graph.json"
            if not graph_file.exists():
                raise ExtractionError(
                    f"Graphify produced no graph.json for {repo_path}. "
                    f"stderr tail: {result.stderr[-2000:]}"
                )

            logger.info("graphify graph.json: %s bytes", graph_file.stat().st_size)
            return json.loads(graph_file.read_text(encoding="utf-8"))
    finally:
        if _tmp_ignore_dir is not None:
            _tmp_ignore_dir.cleanup()
        elif not _ignore_existed:
            (repo_path / ".graphifyignore").unlink(missing_ok=True)
